# netlify.toml for Next.js static export
[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enable = false

# Redirect all traffic to root HTML so that next/router can do its thing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Headers for better performance
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
